use_frameworks!

platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'PUBProxy_Example' do
  pod 'PUBProxy', :path => '../'

  target 'PUBProxy_Tests' do
    inherit! :search_paths

    
  end
end
