use_frameworks!

platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
# iOS16适配pod签名
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
target 'PUBProxy_Example' do
  pod 'PUBProxy', :path => '../'
end
